ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ ru.hukm.petnest.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/petnest"
    url = ${?DATABASE_URL}
    user = "petnest"
}

redis {
    url = "redis://localhost:6379"
    url = ${?REDIS_URL}
}

session {
    header = "X-Session-Id"
    ttlDays = 30
}

metrics {
    user = "prometheus"
}
